Repository DeveloperAcademy-POSTECH/MC2-Team2-GreedySquirrel, pull requests merged in 2022-06, with the labels that each got.

#2 Feature #1 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Feature

#4 [Project] #3 : Add gitignore
  .gitignore
Labels: Project

#6 [Project] #5 : Add Gitattributes
  .gitattributes
Labels: Project

#18 [Feature] #16, #17 : Add ToolDictionaryMainView UI
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
Labels: Feature, ToolDictionaryMainView

#25 [Bug] #24 : resolved error
  campair/campair.xcodeproj/project.pbxproj
Labels: Bug

#22 [Feature] #19, #20 : Add ToolDictionaryDetailView UI
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/View/ToolDictionary/ToolDictionaryDetailView.swift
Labels: Feature, ToolDictionaryDetailView

#27 [Feature] #26 : Add EditorDetailView UI
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Application/Assets.xcassets/exampleEquipment.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/exampleEquipment.imageset/스크린샷 2022-06-13 오후 11.00.00.png
  campair/campair/Application/Assets.xcassets/examplePainting.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/examplePainting.imageset/스크린샷 2022-06-13 오후 9.59.30.png
  campair/campair/Application/Assets.xcassets/moreEquipmentPainting.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/moreEquipmentPainting.imageset/스크린샷 2022-06-13 오후 11.04.47.png
  campair/campair/Application/ColorExtension.swift
  campair/campair/View/Editor/EditorDetailView.swift
Labels: Feature, EditorDetailView

#29 [Refactor] #28 : Change the word "tool" to "equipment"
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/View/EquipmentDictionary/EquipmentDictionaryDetailView.swift
  campair/campair/View/EquipmentDictionary/EquipmentDictionaryMainView.swift
Labels: Refactor, EditorDetailView

#31 [Feature] #30 Add function that returns safeArea top value
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Application/SafeAreaPadding.swift
  campair/campair/View/Editor/EditorDetailView.swift
Labels: Feature, Clean code

#34 [Feature] #33 EditorDetailView Data Binding
  campair/campair/View/Editor/EditorDetailView.swift
  campair/campair/View/EquipmentDictionary/EquipmentDictionaryDetailView.swift
  campair/campair/View/EquipmentDictionary/EquipmentDictionaryMainView.swift
  campair/campair/ViewModel/EditorViewModel.swift
Labels: Feature, EditorDetailView

#41 [Refactor] #38 Rearrange Editor folder
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/View/Editor/Detail/EditorDetailView.swift
  campair/campair/View/Editor/Main/EditorCardView.swift
  campair/campair/View/Editor/Main/EditorEquipListView.swift
  campair/campair/View/Editor/Main/EditorMainView.swift
Labels: Refactor

#47 [Refactor] #37 #46 Divide the editor content version and Divide the EditorDetailView's subViews
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Application/Assets.xcassets/exampleEquipment.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/exampleEquipment.imageset/스크린샷 2022-06-13 오후 11.00.00.png
  campair/campair/Application/Assets.xcassets/exampleEquipment.imageset/스크린샷 2022-06-15 오후 5.29.24.png
  campair/campair/Application/Assets.xcassets/examplePainting.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/examplePainting.imageset/스크린샷 2022-06-13 오후 9.59.30.png
  campair/campair/Application/Assets.xcassets/examplePainting.imageset/스크린샷 2022-06-15 오후 5.27.39.png
  campair/campair/Application/Assets.xcassets/moreEquipmentPainting.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/moreEquipmentPainting.imageset/스크린샷 2022-06-13 오후 11.04.47.png
  campair/campair/Application/Assets.xcassets/moreEquipmentPainting.imageset/스크린샷 2022-06-15 오후 4.38.35.png
  campair/campair/Entity/EditorContent .swift
  campair/campair/Entity/EquipmentContent.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
  campair/campair/View/Editor/Detail/EditorRecommendEquipmentView.swift
  campair/campair/View/Editor/Detail/OpeningEditorView.swift
  campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift
  campair/campair/View/Editor/Detail/ShareRecommendedEquipmentView.swift
Labels: Refactor, EditorDetailView

#50 [Refactor] Fix the padding and text size of the editor detail view by reflecting the hifi
  campair/campair/Application/Assets.xcassets/FindingEquipmentIcon.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/FindingEquipmentIcon.imageset/FindingEquipment.svg
  campair/campair/Application/Assets.xcassets/buttonArrow.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/buttonArrow.imageset/btn_arrow.svg
  campair/campair/Application/Assets.xcassets/contentCard2.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/contentCard2.imageset/card_con.svg
  campair/campair/Application/Assets.xcassets/examplePainting.imageset/스크린샷 2022-06-15 오후 5.27.39.png
  campair/campair/Application/ColorExtension.swift
  campair/campair/Entity/OpeningSection.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
  campair/campair/View/Editor/Detail/EditorRecommendEquipmentView.swift
  campair/campair/View/Editor/Detail/OpeningEditorView.swift
  campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift
  campair/campair/View/Editor/Detail/ShareRecommendedEquipmentView.swift
Labels: Refactor, EditorDetailView

#52 [Feature] Create an equipmentGroups entity and JSON data
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Entity/EquipmentCollection.swift
  campair/campair/Entity/EquipmentCollectionData.json
  campair/campair/Entity/EquipmentGroup.swift
Labels: Feature, ToolDictionaryDetailView

#54 [Refactor] #53 Revise Editor's Entity
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Entity/Dictionary/Equipment.swift
  campair/campair/Entity/Dictionary/EquipmentCollection.swift
  campair/campair/Entity/Dictionary/EquipmentGroup.swift
  campair/campair/Entity/Editor/ContentEquipment.swift
  campair/campair/Entity/Editor/Detail/EditorDetailContent.swift
  campair/campair/Entity/Editor/Detail/EquipmentContent.swift
  campair/campair/Entity/Editor/Detail/OpeningSection.swift
  campair/campair/Entity/Editor/Main/EditorMainCollection.swift
  campair/campair/Entity/Editor/Main/EditorMainContent.swift
  campair/campair/Entity/EditorCollectionData.json
  campair/campair/Entity/EditorContent .swift
  campair/campair/Entity/EditorDetailContentData.json
  campair/campair/Entity/EditorMainCollectionData.json
  campair/campair/Entity/EquipmentCollectionData.json
  campair/campair/Entity/OpeningSection.swift
  campair/campair/Model/EditorRepository.swift
  campair/campair/UseCase/EditorUseCase.swift
  campair/campair/View/ContentView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
  campair/campair/View/Editor/Detail/EditorRecommendEquipmentView.swift
  campair/campair/View/Editor/Detail/OpeningEditorView.swift
  campair/campair/ViewModel/EditorViewModel.swift
Labels: Refactor, EditorMainView, EditorDetailView, Entity

#58 [Refactor] #57 Revise Editor Entity
  campair/campair/Entity/Editor/Main/EditorMainContent.swift
  campair/campair/Entity/EditorMainCollectionData.json
  campair/campair/View/ContentView.swift
Labels: Refactor, EditorDetailView, Entity

#60 [Refactor] delete errors EditorDetailView and modify UI
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Application/ViewExtension.swift
  campair/campair/Entity/Editor/ContentEquipment.swift
  campair/campair/Entity/Editor/Detail/EditorDetailContent.swift
  campair/campair/View/ContentView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
  campair/campair/View/Editor/Detail/EditorRecommendEquipmentView.swift
  campair/campair/View/Editor/Detail/OpeningEditorView.swift
  campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift
  campair/campair/View/Editor/Detail/ShareRecommendedEquipmentView.swift
  campair/campair/ViewModel/EditorViewModel.swift
Labels: Refactor, EditorDetailView, Clean code, Style

#62 [Feature] #61 Fetch Editor Data, Editor Image
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Application/Images/경량_체어.png
  campair/campair/Application/Images/차로_떠나는_피크닉.png
  campair/campair/Entity/Editor/ContentEquipment.swift
  campair/campair/Entity/Editor/Main/EditorMainCollection.swift
  campair/campair/Entity/Editor/Main/EditorMainContent.swift
  campair/campair/Entity/EditorMainCollectionData.json
  campair/campair/Model/EditorRepository.swift
  campair/campair/UseCase/EditorUseCase.swift
  campair/campair/View/ContentView.swift
  campair/campair/View/Editor/Main/EditorCardView.swift
  campair/campair/View/Editor/Main/EditorMainView.swift
  campair/campair/ViewModel/EditorViewModel.swift
Labels: Feature

#65 [Refactor] #63 Break the SwiftLint Line Length rule
  campair/.swiftlint.yml
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Dictionary/DictionaryDetailedView.swift
  campair/campair/Dictionary/DictionaryMainView.swift
  campair/campair/Dictionary/SwiftUIView.swift
  campair/campair/Model/EditorRepository.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
  campair/campair/View/Editor/Detail/EditorRecommendEquipmentView.swift
  campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift
Labels: Refactor, Project

#68 [Refactor] #67 Organizing folder structure
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Application/Images/CardPainting/먹으러_가는_차박.svg
  campair/campair/Application/Images/CardPainting/차로_떠나는_피크닉.png
  campair/campair/Application/Images/Equipment/경량_체어.png
  campair/campair/Application/Images/EquipmentGroup/먹으러_가는_차박.svg
  campair/campair/Json/Editor/EditorDetailContentData.json
  campair/campair/Json/Editor/EditorMainCollectionData.json
  campair/campair/Model/DictionaryRepository.swift
  campair/campair/UseCase/DictionaryUseCase.swift
  campair/campair/Utility/ColorExtension.swift
  campair/campair/Utility/SafeAreaPadding.swift
  campair/campair/Utility/UtilityPlaceHolder.swift
  campair/campair/Utility/ViewExtension.swift
  campair/campair/View/Dictionary/Content/DictionaryContentView.swift
  campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift
  campair/campair/View/Dictionary/Main/DictionaryMainView.swift
  campair/campair/View/EquipmentDictionary/EquipmentDictionaryDetailView.swift
  campair/campair/View/EquipmentDictionary/EquipmentDictionaryMainView.swift
  campair/campair/ViewModel/Dictionary/DictionaryContentViewModel.swift
  campair/campair/ViewModel/Dictionary/DictionaryDetailViewModel.swift
  campair/campair/ViewModel/Dictionary/DictionaryMainViewModel.swift
  campair/campair/ViewModel/Editor/EditorDetailViewModel.swift
  campair/campair/ViewModel/Editor/EditorMainViewModel.swift
Labels: Refactor, Project

#71 [Refactor] #69 adding contents to empty folders
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Entity/Dictionary/Content/temp3.swift
  campair/campair/Entity/Dictionary/Detail/temp2.swift
  campair/campair/Entity/Dictionary/Main/temp1.swift
Labels: Refactor, Entity

#77 [Refactor] #76 Refactor Editor's initializer
  campair/campair/Entity/Editor/ContentEquipment.swift
  campair/campair/Entity/Editor/Main/EditorMainCollection.swift
  campair/campair/Entity/Editor/Main/EditorMainContent.swift
Labels: Refactor, Entity

#85 [Feature] #23 DictionaryEquipmentContentView's hifi UI
  campair/campair/Utility/ViewExtension.swift
  campair/campair/View/Dictionary/Content/DictionaryContentView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
Labels: Feature, EquipmentDictionaryContentView

#87 [Bug] #86 HOTFIX! Multiple commands produce Error
  campair/campair.xcodeproj/project.pbxproj
Labels: Bug

#89 [Feature] #88 add property for connect with EditorMainView
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Application/CampairApp.swift
  campair/campair/Application/Images/Equipment/그릴_스토브.png
  campair/campair/Application/Images/Equipment/돗자리.png
  campair/campair/Application/Images/Equipment/렉사_타프.png
  campair/campair/Application/Images/Equipment/버너_스토브.png
  campair/campair/Application/Images/Equipment/어닝_사이드월.png
  campair/campair/Json/Editor/Detail/Content_1.json
  campair/campair/Json/Editor/Detail/Content_2.json
  campair/campair/Json/Editor/EditorDetailContentData.json
  campair/campair/Model/EditorRepository.swift
  campair/campair/UseCase/EditorUseCase.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
  campair/campair/View/Editor/Detail/OpeningEditorView.swift
  campair/campair/View/Editor/Detail/ShareRecommendedEquipmentView.swift
  campair/campair/ViewModel/Editor/EditorDetailViewModel.swift
Labels: Feature, EditorDetailView

#91 [Feature] #90 Make tabbarUI
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Application/Assets.xcassets/DictionaryTabbarImage.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/DictionaryTabbarImage.imageset/DictionaryTabbarImage.svg
  campair/campair/Application/Assets.xcassets/EditorTabbarImage.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/EditorTabbarImage.imageset/EditorTabbarImage.svg
  campair/campair/Application/CampairApp.swift
  campair/campair/View/TabbarView.swift
Labels: Feature

#99 [Refactor] #97 fix EditorEntity and reflect in EditorViews
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Application/CampairApp.swift
  campair/campair/Application/Images/Equipment/폴딩_테이블.png
  campair/campair/Application/Images/Equipment/경량_의자.png
  campair/campair/Application/Images/Equipment/그릴_오븐.png
  campair/campair/Application/Images/Equipment/렉타_타프.png
  campair/campair/Application/Images/Equipment/미라형_침낭.png
  campair/campair/Application/Images/Equipment/숯_연료_연료통.png
  campair/campair/Application/Images/Equipment/식기_용기.png
  campair/campair/Application/Images/Equipment/아이스박스.png
  campair/campair/Application/Images/Equipment/어닝_사이드월.png
  campair/campair/Application/Images/Equipment/자충_매트.png
  campair/campair/Application/Images/Equipment/자충매트.png
  campair/campair/Application/Images/Equipment/조명_용품.png
  campair/campair/Application/Images/Equipment/폴딩_테이블.png
  campair/campair/Entity/Editor/Detail/OpeningSection.swift
  campair/campair/Entity/Editor/Main/EditorMainContent.swift
  campair/campair/Json/Editor/Detail/Content_1.json
  campair/campair/Json/Editor/Detail/Content_2.json
  campair/campair/Json/Editor/Detail/Content_3.json
  campair/campair/Json/Editor/Detail/Content_4.json
  campair/campair/Json/Editor/EditorMainCollectionData.json
  campair/campair/View/Editor/Detail/OpeningEditorView.swift
  campair/campair/View/Editor/Main/EditorCardView.swift
  campair/campair/View/Editor/Main/EditorEquipListView.swift
  campair/campair/View/Editor/Main/EditorMainView.swift
Labels: Refactor, EditorMainView, EditorDetailView, Entity

#102 Trasnferring Repository to Goban
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Entity/Dictionary/Content/DictionaryEquipmentContent.swift
  campair/campair/Entity/Dictionary/Detail/EquipmentList.swift
  campair/campair/Model/DictionaryRepository.swift
  campair/campair/UseCase/DictionaryDetailCategoryData.json
  campair/campair/UseCase/DictionaryEquipmentContentData.json
  campair/campair/UseCase/DictionaryUseCase.swift
  campair/campair/View/ContentView.swift
  campair/campair/View/Dictionary/Content/DictionaryContentView.swift
  campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift
  campair/campair/ViewModel/Dictionary/DictionaryContentViewModel.swift
  campair/campair/ViewModel/Dictionary/DictionaryDetailViewModel.swift
Labels: Feature

#105 [Bug] #104 fix EditorDetailListVersionView errors
  campair/campair/Application/CampairApp.swift
  campair/campair/Json/Editor/Detail/Content_2.json
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
Labels: Bug, EditorMainView

#107 [Feature] #106 DictionaryContentViewDataBinding
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Json/Dictionary/Equipment/경량_의자.json
  campair/campair/Json/Dictionary/경량_의자.json
  campair/campair/Model/DictionaryRepository.swift
  campair/campair/UseCase/DictionaryUseCase.swift
  campair/campair/View/ContentView.swift
  campair/campair/View/Dictionary/Content/DictionaryContentView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
  campair/campair/ViewModel/Dictionary/DictionaryContentViewModel.swift
Labels: Feature

#110 [Refactor] #109 DictionaryContentView UI
  campair/campair/Application/Assets.xcassets/FoldingChair.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/FoldingChair.imageset/FoldingChair.png
  campair/campair/Application/Assets.xcassets/contentCard1.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/contentCard1.imageset/contentCard1.png
  campair/campair/Application/Assets.xcassets/contentCard2.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/contentCard2.imageset/card_con.svg
  campair/campair/Application/Assets.xcassets/exampleEquipment.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/exampleEquipment.imageset/스크린샷 2022-06-15 오후 5.29.24.png
  campair/campair/Application/Assets.xcassets/paint_1.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_1.imageset/paint_1.svg
  campair/campair/Application/Assets.xcassets/paint_10.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_10.imageset/paint_10.svg
  campair/campair/Application/Assets.xcassets/paint_11.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_11.imageset/paint_11.svg
  campair/campair/Application/Assets.xcassets/paint_12.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_12.imageset/paint_12.svg
  campair/campair/Application/Assets.xcassets/paint_13.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_13.imageset/paint_13.svg
  campair/campair/Application/Assets.xcassets/paint_14.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_14.imageset/paint_14.svg
  campair/campair/Application/Assets.xcassets/paint_15.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_15.imageset/paint_15.svg
  campair/campair/Application/Assets.xcassets/paint_2.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_2.imageset/paint_2.svg
  campair/campair/Application/Assets.xcassets/paint_21.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_21.imageset/paint_21.png
  campair/campair/Application/Assets.xcassets/paint_24.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_24.imageset/paint_24.svg
  campair/campair/Application/Assets.xcassets/paint_3.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_3.imageset/paint_3.svg
  campair/campair/Application/Assets.xcassets/paint_4.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_4.imageset/paint_4.svg
  campair/campair/Application/Assets.xcassets/paint_5.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_5.imageset/paint_5.svg
  campair/campair/Application/Assets.xcassets/paint_6.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_6.imageset/paint_6.svg
  campair/campair/Application/Assets.xcassets/paint_7.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_7.imageset/paint_7.svg
  campair/campair/Application/Assets.xcassets/paint_8.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_8.imageset/paint_8.svg
  campair/campair/Application/Assets.xcassets/paint_9.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/paint_9.imageset/paint_9.svg
  campair/campair/View/Dictionary/Content/DictionaryContentView.swift
  campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift
  campair/campair/View/Dictionary/Main/DictionaryMainView.swift
Labels: Refactor, EquipmentDictionaryContentView

#111 [Feature] #108 Navigation more see equipments at EditorDetailView
  campair/campair/Application/Assets.xcassets/moreEquipmentPainting.imageset/Contents.json
  campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
  campair/campair/View/Editor/Detail/ShareRecommendedEquipmentView.swift
  campair/campair/ViewModel/Dictionary/DictionaryDetailViewModel.swift
Labels: Feature, EquipmentDictionaryDetailView, EditorDetailView

#113 [Feature] #112 Navigation EditorMainView to DictionaryContentView
  campair/campair/View/Editor/Main/EditorMainView.swift
Labels: Feature, EditorMainView, EquipmentDictionaryContentView

#115 [Feature] #114 add toolbar color
  campair/campair/View/TabbarView.swift
Labels: Feature, EquipmentDictionaryMainView, EditorMainView

#116 [Style] #45 Change EditorEquipListView card's CornerRadius
  campair/campair/Application/Assets.xcassets/moreEquipmentPainting.imageset/Contents.json
  campair/campair/Application/Assets.xcassets/moreEquipmentPainting.imageset/스크린샷 2022-06-15 오후 4.38.35.png
  campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift
  campair/campair/View/Editor/Main/EditorEquipListView.swift
Labels: Style

#117 [Feature] #84 DictionaryEquipmentContentView Data Binding
  campair/campair/View/Dictionary/Content/DictionaryContentView.swift
  campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift
  campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift
  campair/campair/View/Editor/Main/EditorMainView.swift
Labels: EquipmentDictionaryContentView, EditorDetailView

#118 [Feature] Depending on Date, change the phase in EditorMainView #40
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Utility/DateExtension.swift
  campair/campair/View/Editor/Main/EditorMainView.swift
Labels: Feature, EditorMainView

#129 [Bug] Get UI confirmation from berry and fix it
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Application/Images/Equipment/간이화장실.png
  campair/campair/Application/Images/Equipment/담요.png
  campair/campair/Application/Images/Equipment/랜턴.png
  campair/campair/Application/Images/Equipment/랜턴걸이_거치대.png
  campair/campair/Application/Images/Equipment/미라형_침낭.png
  campair/campair/Application/Images/Equipment/숯_연료.png
  campair/campair/Application/Images/Equipment/자충_매트.png
  campair/campair/Application/Images/Equipment/캠핑_난방용품.png
  campair/campair/Json/Editor/Detail/Content_3.json
  campair/campair/View/Dictionary/Content/DictionaryContentView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
  campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
  campair/campair/View/Editor/Detail/OpeningEditorView.swift
  campair/campair/View/Editor/Detail/ShareRecommendedEquipmentView.swift
  campair/campair/View/Editor/Main/EditorCardView.swift
  campair/campair/View/Editor/Main/EditorMainView.swift
Labels: Bug

#133 [Refactor] #130 Change todayPhase's context
  campair/campair/Utility/DateExtension.swift
  campair/campair/View/Editor/Main/EditorMainView.swift
Labels: Feature

#138 [Refactor] #137 Fix Some style
  campair/campair.xcodeproj/project.pbxproj
  campair/campair/Application/Images/Equipment/돗자리.png
  campair/campair/View/Dictionary/Main/DictionaryMainView.swift
  campair/campair/View/Editor/Main/EditorEquipListView.swift
  campair/campair/View/Editor/Main/EditorMainView.swift
Labels: Refactor

#146 [Feature] 145 README.md update
  README.md
  imageFiles/dark.png
  imageFiles/light.png
Labels: Project
